databases:
  - name: payclone-db
    databaseName: payclone
    user: payclone_user
    plan: free

services:
  # 1. Service Discovery (Eureka)
  - type: docker
    name: service-discovery
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: service-discovery
    plan: free

  # 2. User Service
  - type: docker
    name: user-service
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: user-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # 3. Wallet Service
  - type: docker
    name: wallet-service
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: wallet-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # 4. Transaction Service
  - type: docker
    name: transaction-service
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: transaction-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
