databases:
  - name: payclone-db
    databaseName: payclone
    user: payclone_user
    plan: free

services:
  - type: web
    name: service-discovery
    dockerfilePath: ./backend/Dockerfile
    plan: free
    env:
      SERVICE_PATH: service-discovery

  - type: web
    name: user-service
    dockerfilePath: ./backend/Dockerfile
    plan: free
    env:
      SERVICE_PATH: user-service
      SPRING_DATASOURCE_URL:
        fromDatabase:
          name: payclone-db
          property: connectionString
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  - type: web
    name: wallet-service
    dockerfilePath: ./backend/Dockerfile
    plan: free
    env:
      SERVICE_PATH: wallet-service
      SPRING_DATASOURCE_URL:
        fromDatabase:
          name: payclone-db
          property: connectionString
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  - type: web
    name: transaction-service
    dockerfilePath: ./backend/Dockerfile
    plan: free
    env:
      SERVICE_PATH: transaction-service
      SPRING_DATASOURCE_URL:
        fromDatabase:
          name: payclone-db
          property: connectionString
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8761/eureka/
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
