# render.yaml - FINAL CORRECTED VERSION (Docker with correct syntax)

databases:
  - name: payclone-db
    databaseName: payclone
    user: payclone_user
    plan: free

services:
  # 1. Service Discovery (Eureka)
  - type: web
    name: service-discovery
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: service-discovery
    plan: free
    
  # 2. User Service
  - type: web
    name: user-service
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: user-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 3. Wallet Service
  - type: web
    name: wallet-service
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: wallet-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 4. Transaction Service
  - type: web
    name: transaction-service
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: transaction-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 5. Notification Service
  - type: web
    name: notification-service
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: notification-service
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
              
  # 6. API Gateway
  - type: web
    name: api-gateway
    runtime: docker
    docker:
      filePath: ./backend/Dockerfile
      context: .
      buildArgs:
        SERVICE_PATH: api-gateway
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/