# render.yaml

databases:
  - name: payclone-db
    databaseName: payclone
    user: payclone_user
    plan: free

services:
  # 1. Service Discovery (Eureka) - Deploys first
  - type: web
    name: service-discovery
    # The 'env' key is removed to let Render auto-detect Java
    rootDir: backend/service-discovery
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    
  # 2. User Service
  - type: web
    name: user-service
    rootDir: backend/user-service
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        # Use the internal service name for communication
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 3. Wallet Service
  - type: web
    name: wallet-service
    rootDir: backend/wallet-service
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 4. Transaction Service
  - type: web
    name: transaction-service
    rootDir: backend/transaction-service
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: payclone-db
          property: connectionString
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
            
  # 5. Notification Service (No Database)
  - type: web
    name: notification-service
    rootDir: backend/notification-service
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/
              
  # 6. API Gateway (Deploys Last)
  - type: web
    name: api-gateway
    rootDir: backend/api-gateway
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-discovery:8761/eureka/